### ISSUE TITLE
i found a bug

### ISSUE THREAD

**Issue by ghost** [ezzerland/EnderpearlPatch#1]
so pretty much stack up 2 blocks then place a long line roof then put trapdoor under the roof and when you try to pearl you cant heres video of it https://streamable.com/evnqz and heres a tip you should make it so if the pearl gets canceled it gives you the pearl back like some hcf servers

**Comment by ezzerland** [comment]
I had initially set trapdoors and half-slabs as full blocks. without consideration for this. I was busy today, but I will work on adding support for this shortly.
