### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by coolpvpv1** [ezzerland/EnderpearlPatch#3]
found another bug if you throw two pearls at fence gates sometimes for some reason the second pearl will go through the fence gates i have no idea why i guess this could be patched by a 16 second pearl cooldown? idk

**Comment by ezzerland** [comment]
Any length of cooldown would fix this. Having said that, I wasn't able to replicate it. Sorry for the super long delayed response. I have been away and not attentive to minecraft plugin stuff.
